import React, { Component, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, ArrowUpRight, Menu, X, Compass, Users, Handshake, ShieldCheck, Search, BookOpen, Network, Layers3 } from 'lucide-react';
import './styles.css';

const REPO='https://github.com/rllibo833-sudo/kawasan-masjid-core';
const MEMORY='https://github.com/rllibo833-sudo/Founder-OS';
const EMAIL='mailto:fadlibo833@gmail.com?subject=Kawasan%20Masjid%20%E2%80%94%20Peluang%20atau%20Kebutuhan';
const BASE='/kawasan-masjid-public/';
const links=[
  ['vision.html','Visi','Vision'],
  ['ecosystem.html','Ekosistem','Ecosystem'],
  ['system.html','Sistem','System'],
  ['research.html','Riset','Research'],
  ['collaborate.html','Kolaborasi','Collaborate'],
  ['about.html','Tentang','About'],
];

const systems=['Ibadah & kehidupan sipil','Pendidikan & riset','Pangan & pertanian','Air & ekologi','Energi & utilitas','Ekonomi lokal','Ekosistem digital','Hunian & ruang publik'];

class AppErrorBoundary extends Component{
  constructor(p){super(p);this.state={hasError:false}}
  static getDerivedStateFromError(){return {hasError:true}}
  render(){return this.state.hasError?<main className="runtimeFallback"><div><span className="eyebrow">KAWASAN MASJID 1.000 HA</span><h1>Halaman sedang memulihkan tampilan.</h1><p>Terjadi masalah saat memuat antarmuka. Silakan muat ulang halaman atau kembali ke beranda.</p><a className="button primary" href={BASE}>Kembali ke beranda <ArrowRight/></a></div></main>:this.props.children}
}

function Header({lang,setLang}){
 const [open,setOpen]=useState(false);
 const current=window.location.pathname.split('/').pop()||'index.html';
 return <header className="header">
  <a className="brand" href={BASE} onClick={()=>setOpen(false)}><span className="brandMark">KM</span><span className="brandText"><strong>Kawasan Masjid</strong><small>1.000 Ha · Open Project</small></span></a>
  <button className="mobileMenu" aria-label="Menu" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>
  <nav className={open?'nav navOpen':'nav'}>
   {links.map(([file,id,en])=><a key={file} className={current===file?'activeNav':''} href={BASE+file} onClick={()=>setOpen(false)}>{lang==='id'?id:en}</a>)}
   <a href={MEMORY} target="_blank" rel="noreferrer" onClick={()=>setOpen(false)}>Founder-OS <ArrowUpRight/></a>
   <button className="languageButton" onClick={()=>setLang(lang==='id'?'en':'id')}>{lang==='id'?'EN':'ID'}</button>
  </nav>
 </header>
}

function Footer({lang}){
 return <footer className="footer"><div className="footerBrand"><strong>Kawasan Masjid 1.000 Ha</strong><p>{lang==='id'?'Fondasi digital pertama menuju visi jangka panjang Islamic Eco-City.':'The digital foundation for a long-term Islamic Eco-City vision.'}</p></div><div className="footerLinks"><a href={REPO}>CORE Engine <ArrowUpRight/></a><a href={MEMORY}>Founder-OS <ArrowUpRight/></a><a href={EMAIL}>Contact <ArrowUpRight/></a></div><div className="footerBottom"><span>© Kawasan Masjid 1.000 Ha</span><span>No Proof, No Claim.</span></div></footer>
}

function PageShell({children,lang,setLang}){return <div className="site"><Header lang={lang} setLang={setLang}/>{children}<Footer lang={lang}/></div>}
function Eyebrow({children,dark=false}){return <div className={dark?'eyebrow darkEyebrow':'eyebrow'}>{children}</div>}
function PageHero({kicker,title,lead,number='01'}){
 return <section className="pageHero"><div className="pageHeroGlow"/><div className="pageHeroInner"><Eyebrow>{number} / {kicker}</Eyebrow><h1>{title}</h1><p>{lead}</p></div></section>
}
function CTA({href=EMAIL,children='Mulai percakapan'}){return <a className="button primary" href={href}>{children}<ArrowUpRight/></a>}
function Card({icon:Icon,title,text,href}){
 return <article className="featureCard"><div className="featureIcon"><Icon/></div><h3>{title}</h3><p>{text}</p>{href&&<a className="cardLink" href={href}>Jelajahi <ArrowRight/></a>}</article>
}

function Home({lang}){
 const id=lang==='id';
 return <main>
  <section className="hero homeHero"><div className="heroGlow"/><div className="heroContent"><Eyebrow>OPEN PROJECT · {id?'VISI JANGKA PANJANG':'LONG-TERM VISION'}</Eyebrow><h1>{id?'Membangun kawasan berpusat pada masjid sebagai satu ekosistem kehidupan.':'Building a mosque-centered community as one living ecosystem.'}</h1><p className="heroLead">{id?'Kawasan Masjid 1.000 Ha adalah visi jangka panjang Islamic Eco-City. Fondasi pertama yang sedang dibangun adalah ekosistem digital: tempat orang menemukan kebutuhan, kemampuan, riset, kolaborasi, dan peluang yang dapat diuji dengan bukti.':'Kawasan Masjid 1.000 Ha is a long-term Islamic Eco-City vision. The first foundation is a digital ecosystem where needs, capabilities, research, collaboration, and opportunities can be discovered and tested with evidence.'}</p><div className="heroActions"><a className="button primary" href={BASE+'collaborate.html'}>{id?'Saya punya kebutuhan':'I have a need'}<ArrowRight/></a><a className="button secondary" href={BASE+'about.html'}>{id?'Kenali sistem':'Understand the system'}<ArrowRight/></a></div><div className="truthLine"><span><b>1.000</b><small>Ha envisioned</small></span><span><b>08</b><small>connected systems</small></span><span><b>01</b><small>direction</small></span></div></div></section>
  <section className="section homeIntro"><div className="sectionIntro"><div><Eyebrow dark>01 / ENTRY POINT</Eyebrow><h2>{id?'Sebuah website resmi untuk memahami, meninjau, dan menemukan jalan masuk ke ekosistem.':'An institutional front door to understand, review, and find a way into the ecosystem.'}</h2></div><div className="introText"><p>{id?'Mulai dari halaman yang Anda butuhkan. Detail visi, delapan sistem, arsitektur kerja, riset, dan kolaborasi kini dipisahkan agar project dapat dijelajahi seperti sebuah institusi — bukan sekadar landing page.':'Start with the page you need. Vision, eight systems, operating architecture, research, and collaboration are separated so the project can be explored like an institution — not a single landing page.'}</p></div></div></section>
  <section className="section creamSection"><div className="centerHeading"><Eyebrow dark>02 / EXPLORE</Eyebrow><h2>{id?'Pilih bagian yang ingin Anda pahami.':'Choose what you want to understand.'}</h2></div><div className="featureGrid"><Card icon={Compass} title={id?'Visi':'Vision'} text={id?'Mengapa kawasan ini dimulai dari fondasi digital dan bagaimana visi fisik 1.000 Ha ditempatkan sebagai tujuan jangka panjang.':'Why the project starts with a digital foundation and how the 1,000 Ha physical vision remains a long-term destination.'} href={BASE+'vision.html'}/><Card icon={Network} title={id?'Ekosistem':'Ecosystem'} text={id?'Delapan sistem yang dirancang saling memperkuat dalam satu arah kehidupan.':'Eight systems designed to reinforce one another in one direction.'} href={BASE+'ecosystem.html'}/><Card icon={Layers3} title={id?'Sistem':'System'} text={id?'Batas PUBLIC, CORE, MEMORY dan alur dari visi menuju evidence dan implementasi.':'The PUBLIC, CORE, MEMORY boundary and the flow from vision to evidence and implementation.'} href={BASE+'system.html'}/><Card icon={BookOpen} title={id?'Riset':'Research'} text={id?'Tempat untuk evidence, blueprint, studi, dan pengetahuan yang dapat ditinjau.':'A home for evidence, blueprints, studies, and reviewable knowledge.'} href={BASE+'research.html'}/></div></section>
  <section className="section darkSection homeCTA"><div className="sectionHeading"><div><Eyebrow>03 / NEXT STEP</Eyebrow><h2>{id?'Punya kebutuhan atau kemampuan yang relevan?':'Have a real need or relevant capability?'}</h2></div><p>{id?'Masuk melalui halaman kolaborasi. Kita mulai dari kebutuhan atau kontribusi yang konkret, lalu menjaga proses tetap terukur dan berbasis bukti.':'Enter through collaboration. Start with a concrete need or contribution, then keep the process measurable and evidence-based.'}</p></div><div className="sectionActions"><CTA href={BASE+'collaborate.html'}>{id?'Buka jalur kolaborasi':'Open collaboration'}</CTA><a className="button secondary" href={BASE+'about.html'}>{id?'Tentang project':'About the project'}<ArrowRight/></a></div></section>
 </main>
}

function Vision({lang}){const id=lang==='id';return <main><PageHero number="01" kicker={id?'VISI':'VISION'} title={id?'Visi besar dimulai dari fondasi yang dapat dibuktikan.':'A large vision starts with a foundation that can be proven.'} lead={id?'Kawasan Masjid 1.000 Ha adalah tujuan fisik jangka panjang. Tahap pertama bukan membangun lahannya, tetapi membangun ekosistem digital yang mampu menarik manusia, kebutuhan, pengetahuan, kolaborasi, dan peluang.':'Kawasan Masjid 1,000 Ha is the long-term physical destination. The first stage is not building the land, but building a digital ecosystem capable of attracting people, needs, knowledge, collaboration, and opportunity.'}/><section className="section"><div className="editorialGrid"><div><Eyebrow dark>01 / NORTH STAR</Eyebrow><h2>{id?'Masjid sebagai orientasi, kawasan sebagai ekosistem.':'The mosque as orientation, the kawasan as an ecosystem.'}</h2></div><div className="prose"><p>{id?'Visi ini menghubungkan ibadah, pendidikan, pangan, air, energi, ekonomi, teknologi, hunian, dan ruang publik dalam satu arah. Fisiknya dibangun bertahap setelah sistem, kebutuhan, dan evidence cukup kuat.':'The vision connects worship, education, food, water, energy, economy, technology, housing, and public space in one direction. Physical implementation comes in stages after the system, needs, and evidence are strong enough.'}</p><p>{id?'Karena itu, digital bukan pengganti kawasan. Digital adalah fondasi awal yang membuat kawasan dapat dirancang dengan lebih sadar.':'Digital is not a replacement for the kawasan. It is the first foundation that allows the physical destination to be designed with greater evidence and discipline.'}</p></div></div></section><section className="section creamSection"><div className="centerHeading"><Eyebrow dark>02 / PRINCIPLES</Eyebrow><h2>{id?'Empat prinsip pengembangan.':'Four development principles.'}</h2></div><div className="featureGrid four"><Card icon={ShieldCheck} title="No Proof, No Claim" text={id?'Yang belum terbukti tetap disebut sebagai rencana atau eksperimen.':'Unproven outcomes remain plans or experiments.'}/><Card icon={Search} title={id?'Digital first':'Digital first'} text={id?'Bangun kemampuan yang bisa diuji sebelum memperluas bentuk fisik.':'Build testable capabilities before expanding physical form.'}/><Card icon={Users} title={id?'Human first':'Human first'} text={id?'Nilai ditentukan oleh kebutuhan dan penggunaan nyata.':'Value is determined by real needs and real use.'}/><Card icon={ArrowRight} title={id?'Bertahap':'Phased'} text={id?'Perluas hanya ketika evidence dan nilai mendukung.':'Expand only when evidence and value support it.'}/></div></section></main>}

function Ecosystem({lang}){const id=lang==='id';return <main><PageHero number="02" kicker={id?'EKOSISTEM':'ECOSYSTEM'} title={id?'Delapan sistem. Satu arah.':'Eight systems. One direction.'} lead={id?'Kawasan dipahami sebagai jaringan kehidupan, bukan kumpulan bangunan yang berdiri sendiri.':'The kawasan is a living network, not a collection of isolated buildings.'}/><section className="section"><div className="sectionHeading"><div><Eyebrow dark>01 / CONNECTED SYSTEMS</Eyebrow><h2>{id?'Setiap sistem punya fungsi, tetapi tidak berdiri sendiri.':'Each system has a role, but none stands alone.'}</h2></div><p>{id?'Kekuatan visi berada pada hubungan antarsistem: manusia, layanan, ekonomi, alam, ruang, dan teknologi saling memberi nilai.':'The strength of the vision lies in the relationships between people, services, economy, nature, space, and technology.'}</p></div><div className="systemGrid">{systems.map((s,i)=><div className="systemItem" key={s}><span>0{i+1}</span><strong>{s}</strong></div>)}</div></section><section className="section creamSection"><div className="editorialGrid"><div><Eyebrow dark>02 / DESIGN LOGIC</Eyebrow><h2>{id?'Bukan delapan proyek terpisah.':'Not eight separate projects.'}</h2></div><div className="prose"><p>{id?'Ekosistem digital membantu menjaga agar setiap eksperimen dapat dipetakan kembali ke kebutuhan dan sistem yang lebih besar.':'The digital ecosystem helps each experiment remain connected to a real need and the wider system.'}</p><p>{id?'Tujuannya bukan membuat semuanya sekaligus, tetapi menemukan komponen yang benar-benar berguna lalu menghubungkannya secara bertahap.':'The goal is not to build everything at once, but to find useful components and connect them gradually.'}</p></div></div></section></main>}

function System({lang}){const id=lang==='id';const steps=[['01','VISI',id?'Arah besar, tujuan, prinsip, dan batasan project.':'Direction, purpose, principles, and constraints.'],['02','DIGITAL',id?'Riset, dokumen, data, tools, dan koordinasi.':'Research, documents, data, tools, and coordination.'],['03','EVIDENCE',id?'Apa yang benar-benar ada dipisahkan dari asumsi.':'What exists is separated from assumptions.'],['04','FOUNDER GATE',id?'Validasi dan keputusan strategis naik ke Founder.':'Strategic validation and decisions reach the Founder.'],['05','IMPLEMENTASI',id?'Komponen kecil diuji sebelum diperbesar.':'Small useful components are tested before expansion.']];return <main><PageHero number="03" kicker={id?'SISTEM':'SYSTEM'} title={id?'Sebuah arsitektur dengan batas yang jelas.':'An architecture with clear boundaries.'} lead={id?'PUBLIC membuka pintu. CORE menjalankan mesin. Founder-OS menjaga arah dan keputusan.':'PUBLIC opens the door. CORE runs the engine. Founder-OS keeps direction and decisions.'}/><section className="section systemFlowPage"><div className="sectionHeading"><div><Eyebrow dark>01 / OPERATING FLOW</Eyebrow><h2>{id?'Dari visi menuju implementasi tanpa melompati evidence.':'From vision to implementation without skipping evidence.'}</h2></div><p>{id?'Setiap lapisan memiliki tanggung jawab sendiri agar sistem tidak bercampur dan klaim tetap dapat diaudit.':'Each layer has a distinct responsibility so the system remains auditable and claims stay grounded.'}</p></div><div className="systemFlow">{steps.map((s,i)=><React.Fragment key={s[1]}><article className="systemFlowCard"><span>{s[0]}</span><strong>{s[1]}</strong><p>{s[2]}</p></article>{i<steps.length-1&&<div className="systemFlowArrow">→</div>}</React.Fragment>)}</div></section><section className="section creamSection"><div className="systemBoundary"><div><strong>PUBLIC</strong><span>{id?'Penemuan, pemahaman, reputasi, dan peluang eksternal.':'Discovery, understanding, reputation, and external opportunity.'}</span></div><div><strong>CORE</strong><span>{id?'Runtime, backend, Supabase, evidence, workflows, dan ekonomi.':'Runtime, backend, Supabase, evidence, workflows, and economics.'}</span></div><div><strong>MEMORY</strong><span>{id?'Keputusan Founder, constraint, continuity, dan governance.':'Founder decisions, constraints, continuity, and governance.'}</span></div></div></section></main>}

function Research({lang}){const id=lang==='id';return <main><PageHero number="04" kicker={id?'RISET & EVIDENCE':'RESEARCH & EVIDENCE'} title={id?'Pengetahuan harus dapat ditinjau sebelum menjadi keyakinan.':'Knowledge should be reviewable before it becomes conviction.'} lead={id?'Halaman ini menjadi rumah publik untuk riset, blueprint, evidence, eksperimen, dan dokumen yang aman untuk dibagikan.':'This is the public home for research, blueprints, evidence, experiments, and safe-to-share documents.'}/><section className="section"><div className="featureGrid four"><Card icon={BookOpen} title="Research" text={id?'Studi, analisis, dan pembelajaran yang mendukung keputusan.':'Studies, analysis, and learning that support decisions.'}/><Card icon={ShieldCheck} title="Evidence" text={id?'Bukti yang membedakan kondisi aktual dari rencana.':'Evidence separating current truth from plans.'}/><Card icon={Compass} title="Blueprint" text={id?'Kerangka konseptual menuju implementasi bertahap.':'Conceptual frameworks toward phased implementation.'}/><Card icon={Layers3} title="Experiments" text={id?'Uji kecil untuk menemukan apa yang benar-benar berguna.':'Small tests to discover what is actually useful.'}/></div></section><section className="section creamSection"><div className="editorialGrid"><div><Eyebrow dark>02 / PUBLIC EVIDENCE</Eyebrow><h2>{id?'Tidak semua data harus publik. Yang publik harus aman dan jujur.':'Not all data must be public. What is public must be safe and honest.'}</h2></div><div className="prose"><p>{id?'PUBLIC hanya menampilkan subset yang aman. Data runtime, kredensial, keputusan internal, dan informasi sensitif tetap berada di CORE atau Founder-OS.':'PUBLIC exposes only a safe subset. Runtime data, credentials, internal decisions, and sensitive information remain in CORE or Founder-OS.'}</p></div></div></section></main>}

function Collaborate({lang}){const id=lang==='id';return <main><PageHero number="05" kicker={id?'KOLABORASI':'COLLABORATE'} title={id?'Mulai dari kebutuhan nyata, bukan dari janji besar.':'Start with a real need, not a grand promise.'} lead={id?'Jalur kolaborasi adalah pintu masuk bagi kebutuhan, pilot, kemampuan, partner, atau peluang implementasi yang konkret.':'The collaboration path is an entry point for concrete needs, pilots, capabilities, partners, or implementation opportunities.'}/><section className="section"><div className="collaborationBox"><div className="collaborationMain"><Eyebrow dark>01 / PATH</Eyebrow><h2>{id?'Request → Qualify → Founder Review → Deliver → Prove':'Request → Qualify → Founder Review → Deliver → Prove'}</h2><p>{id?'Kami mencari hubungan yang menghasilkan langkah nyata dan dapat diterima. Tidak ada klaim partner, customer, payment, atau implementasi fisik tanpa bukti terverifikasi.':'We look for relationships that produce a real, accepted next step. No partner, customer, payment, or physical implementation is claimed without verified evidence.'}</p><div className="flow"><span>Request</span><i>→</i><span>Qualify</span><i>→</i><span>Founder Review</span><i>→</i><span>Deliver</span><i>→</i><span>Prove</span></div></div><div className="collaborationOffer"><span className="offerLabel">INITIAL ECONOMIC EXPERIMENT</span><h3>AI-assisted Operations / Research Pack</h3><p>{id?'Decision brief, evidence register, recommended workflow, implementation checklist, dan limitations untuk kebutuhan konkret.':'Decision brief, evidence register, recommended workflow, implementation checklist, and limitations for a concrete need.'}</p><strong>Target pilot mulai Rp100.000</strong><small>{id?'Target penawaran, bukan klaim revenue.':'Offer target, not claimed revenue.'}</small><CTA>{id?'Kirim kebutuhan konkret':'Send a concrete request'}</CTA></div></div><div className="noClaim"><ShieldCheck/><span><strong>No Proof, No Claim.</strong> {id?'Yang belum terbukti tetap disebut sebagai target, rencana, atau eksperimen.':'Unproven outcomes remain targets, plans, or experiments.'}</span></div></section></main>}

function About({lang}){const id=lang==='id';return <main><PageHero number="06" kicker={id?'TENTANG PROJECT':'ABOUT'} title={id?'Tiga lapisan. Satu arah.':'Three layers. One direction.'} lead={id?'PUBLIC, CORE, dan Founder-OS dibangun dengan peran berbeda agar project tetap dapat berkembang tanpa kehilangan arah.':'PUBLIC, CORE, and Founder-OS have distinct roles so the project can grow without losing direction.'}/><section className="section"><div className="featureGrid"><Card icon={Compass} title="PUBLIC" text={id?'Pintu masuk publik: discovery, storytelling, opportunity, dan reputasi.':'Public front door: discovery, storytelling, opportunity, and reputation.'}/><Card icon={Layers3} title="CORE" text={id?'Mesin kanonik: runtime, backend, evidence, economics, dan capabilities.':'Canonical engine: runtime, backend, evidence, economics, and capabilities.'}/><Card icon={ShieldCheck} title="Founder-OS" text={id?'Memory dan operating system untuk keputusan, constraint, continuity, dan Founder Gate.':'Memory and operating system for decisions, constraints, continuity, and Founder Gate.'}/></div></section><section className="section creamSection"><div className="editorialGrid"><div><Eyebrow dark>02 / CURRENT TRUTH</Eyebrow><h2>{id?'Yang benar hari ini harus tetap terlihat.':'Today’s truth must remain visible.'}</h2></div><div className="truthItems largeTruth"><div><strong>Digital foundation</strong><span>{id?'Sedang dibangun':'Being built'}</span></div><div><strong>Physical kawasan</strong><span>{id?'Belum direalisasikan':'Not implemented'}</span></div><div><strong>Customers</strong><span>0 verified</span></div><div><strong>Partners</strong><span>0 verified</span></div><div><strong>Payment</strong><span>Rp0 verified</span></div></div></div></section><section className="section darkSection"><div className="sectionHeading"><div><Eyebrow>03 / FOUNDER GATE</Eyebrow><h2>{id?'AI membantu pekerjaan. Founder memegang arah.':'AI helps the work. The Founder holds the direction.'}</h2></div><p>{id?'Founder-OS memastikan keputusan strategis, komitmen eksternal, dan perubahan consequential tetap melewati Founder Gate.':'Founder-OS ensures strategic decisions, external commitments, and consequential changes pass through the Founder Gate.'}</p></div><div className="sectionActions"><a className="button primary" href={MEMORY}>Buka Founder-OS <ArrowUpRight/></a></div></section></main>}

function App(){
 const [lang,setLang]=useState('id');
 const file=window.location.pathname.split('/').pop()||'index.html';
 let Page=Home;
 if(file==='vision.html')Page=Vision;
 else if(file==='ecosystem.html')Page=Ecosystem;
 else if(file==='system.html')Page=System;
 else if(file==='research.html')Page=Research;
 else if(file==='collaborate.html')Page=Collaborate;
 else if(file==='about.html')Page=About;
 return <PageShell lang={lang} setLang={setLang}><Page lang={lang}/></PageShell>;
}
const root=document.getElementById('root');
if(!root)throw new Error('Root element #root is missing.');
createRoot(root).render(<AppErrorBoundary><App/></AppErrorBoundary>);
